### ISSUE TITLE
Request error with status code "401" for url

### ISSUE THREAD

**Issue by nightvis** [gabrielfs7/google-trends#11]
GoogleTrends error: Request error with status code "401" for url

**Comment by gabrielfs7** [comment]
Hi @nightvis can you please check if the date interval you sent was less or equal 1 day? We have a current limitation with this. Can you please provide the PHP code you used to get this error?

Generally google returns 401 when there is an error in the request body

**Comment by jzd16boof** [comment]
I encountered the same problem. When I searched with RelatedQueriesSearch and RelatedTopicsSearch, I got a 401 error. Using the other two methods, I can return data normally.

Are the examples on the homepage generic, or do the RelatedQueriesSearch and RelatedTopicsSearch methods have different parameter formats? Can you give a comparison table of the parameters?

**Comment by rzvngbrl** [comment]
Hey,
Yes, I have the same problem with the 401, and I can't really find the way why it does this, I've made the requests on parallel on the google trends platform, and the only difference is a date format, we are sending **now -7 days** instead of the date, however that did not fix the problem

Gabriel, do you have any ideas?

Thanks,
Gabriel :)

**Comment by jzd16boof** [comment]
Hello,
I am using another Google Trends interface now. The URL is https://github.com/x-fran/g-trends. This interface is very accurate and can be used normally after my test. If you are interested, you can try it (if you want to search for your custom time, please use 2020-06-01 2020-06-10, this format, example There will be problems with the time search method in ).




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Razvan Gabriel Tudor"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 凌晨1:53
收件人:&nbsp;"gabrielfs7/google-trends"<google-trends@noreply.github.com&gt;;
抄送:&nbsp;"残骸のなかに"<317160138@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gabrielfs7/google-trends] Request error with status code "401" for url (#11)





 
Hey,
 Yes, I have the same problem with the 401, and I can't really find the way why it does this, I've made the requests on parallel on the google trends platform, and the only difference is a date format, we are sending now -7 days instead of the date, however that did not fix the problem
 
Gabriel, do you have any ideas?
 
Thanks,
 Gabriel :)

**Comment by titomiguelcosta** [comment]
I am experiencing the same issue, 401 on both RelatedQueriesSearch and RelatedTopicsSearch. Any ideas?

This is what I get when I execute the index.php

`{"exception":"GSoares\\GoogleTrends\\Error\\GoogleTrendsException","error":"GoogleTrendserror:Requesterrorwithstatuscode\"401\"forurl\"https:\/\/trends.google.com\/trends\/api\/widgetdata\/relatedsearches?hl=en-US&tz=-60&req={"restriction":{"geo":{"country":"US"},"time":"2020-06-21+2020-06-28","originalTimeRangeForExploreUrl":"2020-06-21+2020-06-28","complexKeywordsRestriction":{"keyword":[{"type":"BROAD","value":"google"}]}},"keywordType":"QUERY","metric":["TOP","RISING"],"trendinessSettings":{"compareTime":"2020-06-13+2020-06-20"},"requestOptions":{"property":"","backend":"IZG","category":0},"language":"en"}&token=APP6_UEAAAAAXvnCwKQjMN3lTStVTrXG-S44JMeiVWHt\""}`

**Comment by gabrielfs7** [comment]
Sorry for the late response, but I did not have time to work on this before. :) 

Those issues were addressed here: https://github.com/gabrielfs7/google-trends/tree/2.0.0

The issue was because I have to send the same query to google to retrieve the token, but they changed the URL parameters, so I have to update the library.
