### ISSUE TITLE
Unable to get 'Rising' metrics

### ISSUE THREAD

**Issue by shivy23** [gabrielfs7/google-trends#9]
I'm only getting 'Top' metrics, not the 'Rising'. Below is the code I'm running in PHP.

`require __DIR__ . '/../vendor/autoload.php';

header('Content-Type', 'application/json');

try {
$searchFilter = (new GSoares\GoogleTrends\Search\SearchFilter())
        ->withCategory(0) //All categories
        ->withSearchTerm('Google')
        ->withLocation('US')
        ->withinInterval(
            new DateTimeImmutable('now -7 days'),
            new DateTimeImmutable('now')
        )
        ->withLanguage('en-US')
        ->considerWebSearch()
        # ->considerImageSearch() // Consider only image search
        # ->considerNewsSearch() // Consider only news search
        # ->considerYoutubeSearch() // Consider only youtube search
        # ->considerGoogleShoppingSearch() // Consider only Google Shopping search
        ->withTopMetrics()
        ->withRisingMetrics();

    $result = (new GSoares\GoogleTrends\Search\RelatedQueriesSearch())
    ->search($searchFilter)
    ->jsonSerialize();

    echo json_encode($result);
}	catch (Throwable $exception) {
    echo json_encode(
        [
            'exception' => get_class($exception),
            'error' => $exception->getMessage()
        ]
    );
}`

**Comment by gabrielfs7** [comment]
Hello @shivy23 ,

It is actually returning both metrics together (TOP and RISING). It is not possible to isolate in different requests only TOP or only RISING. Indeed the response was not clear, so I fixed this and extended the response with the attribute `metricType`. You can now get in the response only the ones that matter for you or both!

You can have this fixed in the version 1.2.2 https://github.com/gabrielfs7/google-trends/tree/1.2.2

Thanks for the heads up! :)
